image: Visual Studio 2019
configuration: Release
platform: Any CPU

environment:
  IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1

install:
  - choco install gitversion.portable -y -pre

before_build:
  - ps: gitversion /l console /output buildserver
  - ps: $env:PackageVersion=$env:GitVersion_NuGetVersion
  - ps: $env:AssemblyVersion=$env:GitVersion_AssemblySemVer
  - ps: $env:FileVersion=$env:GitVersion_MajorMinorPatch.0
  - ps: $env:InformationalVersion=$env:GitVersion_InformationalVersion
  - ps: $env:PackageOutputPath="$env:APPVEYOR_BUILD_FOLDER\pkg"
  - nuget restore
  - dotnet restore
  
build:
  verbosity: minimal
  project: Cogito.Json.Schema.sln

test:
  assemblies:
  - '**/Tests.dll'

artifacts:
  - path: pkg\*.nupkg
    name: Cogito.Json.Schema
    
-
  branches:
    only:
    - master
    - develop
  deploy:
    provider: NuGet
    server: https://nuget.pkg.github.com/alethic/index.json
    username: wasabii
    api_key:
      secure: u7+1z/CZGBli+CiDxHSQetMjE1dbaf1f9eJtSCb8wifl7s1+AdnhWjnsjGQaEsAw
    skip_symbols: false
    symbol_server:
    artifact: /.*\.nupkg/
