<Project Sdk="Microsoft.Build.NoTargets">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <TestTarget Include="Cogito.Json.Schema.Tests|net47" ProjectName="Cogito.Json.Schema.Tests" TargetFramework="net47" />
        <TestTarget Include="Cogito.Json.Schema.Tests|net8.0" ProjectName="Cogito.Json.Schema.Tests" TargetFramework="net8.0" />
    </ItemGroup>

    <!-- Runs once per TFM to generate individual output. -->
    <Target Name="GetCopyToOutputDirectoryItemsByTestTarget" BeforeTargets="BeforeBuild" Inputs="@(TestTarget)" Outputs="%(Identity)\null">

        <PropertyGroup>
            <_ProjectName>%(TestTarget.ProjectName)</_ProjectName>
            <_ProjectFile>%(TestTarget.ProjectFile)</_ProjectFile>
            <_ProjectFile Condition=" '$(_ProjectFile)' == '' And Exists('..\$(_ProjectName)\$(_ProjectName).csproj') ">..\$(_ProjectName)\$(_ProjectName).csproj</_ProjectFile>
            <_TargetFramework>%(TestTarget.TargetFramework)</_TargetFramework>
        </PropertyGroup>

        <ItemGroup>
            <PublishProjectReference Include="$(_ProjectFile)">
                <SetTargetFramework>TargetFramework=$(_TargetFramework)</SetTargetFramework>
                <PublishTargetPath>$(_ProjectName)\$(_TargetFramework)</PublishTargetPath>
                <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            </PublishProjectReference>
        </ItemGroup>
    </Target>

</Project>
